### ISSUE TITLE
Instantiating problem

### ISSUE THREAD

**Issue by EkremSel** [egrillot/Exact-Hidden-Markov-Models#1]
I have changed the module name from RF-HMM to RHFMM, because it was throwing a syntax error. When I try to instantiate it, it is throwing the below error.  Thanks in advance

TypeError                                 Traceback (most recent call last)
Cell In [15], line 1
----> 1 model=RFHMM.RF_HMM(2,threshold=0.7)

File ~\Exact-Hidden-Markov-Models\RFHMM\RFHMM.py:75, in RF_HMM.__init__(self, n_states, covars_type, evaluation_type, params, threshold, fixed_threshold, percentage_threshold)
     74 def __init__(self,n_states,covars_type='diag',evaluation_type='acc',params='stmc',threshold=0.70,fixed_threshold=True,percentage_threshold=False):
---> 75     self.model=CustomGaussianHmm(n_components=n_states,covariance_type=covars_type,params=params,threshold=threshold,fixed_threshold=fixed_threshold,percentage_threshold=percentage_threshold)

TypeError: CustomGaussianHmm.__init__() missing 13 required positional arguments: 'min_covar', 'startprob_prior', 'transmat_prior', 'means_prior', 'means_weight', 'covars_prior', 'covars_weight', 'algorithm', 'random_state', 'n_iter', 'tol', 'verbose', and 'init_params'

**Comment by egrillot** [comment]
Hi @EkremSel ,

Thanks for raising this error. It was due to inheritance issues with the GaussianHMM class from hmmlearn. Could you please try again tu run your code with my modifications ?

**Comment by EkremSel** [comment]
Thanks. That did the trick.
